### ISSUE TITLE
Specify LICENSE

### ISSUE THREAD

**Issue by womfoo** [tmtk75/librarian-puppet-go#5]
Hi, First of all thanks for writing this tool. I am in the process of packaging this for NixOS and it would be great if we can mark this as a F/OSS.

**Comment by tmtk75** [comment]
@womfoo Hi, I've missed this issue until now. Really sorry.
You can use this code under MIT license.
https://github.com/tmtk75/librarian-puppet-go/blob/master/LICENSE.md
